### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by Janych**

### CODE REVIEW

**Comment by palfrey** [comment]
Hi! I'm having a look over this repository again. If you can fix the conflicts in the next month I'll re-review, otherwise I'll close this PR.

**Comment by Janych** [comment]
Hi. I fixed it.

**Comment by palfrey** [comment]
Sorry, but I've just merged https://github.com/palfrey/rhythmbox-tray-icon/pull/8 which I think makes this obsolete?

**Comment by Janych** [comment]
Yes, but I think my version is much simpler.

**Comment by palfrey** [comment]
Closed as the conflicts aren't resolved. Please reopen if conflicts can be resolved and brought in line with the current master.

**Pull request closed without merging**
